# Generated by Django 5.2.4 on 2025-07-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mshop', '0003_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_addrress',
            new_name='customer_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
