# Generated by Django 5.2.4 on 2025-07-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mshop', '0005_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
